# Generated by Django 3.1.4 on 2020-12-27 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='bathroooms',
            new_name='bathrooms',
        ),
    ]
